name: ssh-action-uwu
description: 'Run commands on your vps after deploy'
author: 'sebastianjnuwu'
branding:
  icon: 'terminal'
  color: 'gray-dark'

inputs:
  IP:
    description: ''
    required: true
  USER:
    description: ''
    required: true
  KEY:
    description: ''
    required: true
  REPO:
    description: ''
    required: true
  FOLDER:
    description: ''
    required: true
  RUN: 
    description: ''
    required: true

runs:
  using: 'composite'
  steps:
    - name: 🗿 Creating ssh files...
      run: |
        mkdir -p ~/.ssh/
        echo "${{ inputs.KEY }}" > ~/.ssh/ssh.key
        chmod 600 ~/.ssh/ssh.key
      shell: bash
    - name: 🍷 Setting the ssh Key...
      run: |
        cat >>~/.ssh/config <<END
        Host ssh
          HostName ${{ inputs.IP }}
          User ${{ inputs.USER }}
          Port 22
          IdentityFile ~/.ssh/ssh.key
          StrictHostKeyChecking no
        END
      shell: bash
    - name: 💧 deploy to vps...
      run: |
       cd ..
       echo "${{ inputs.RUN }}"
 #      scp -r ${{ inputs.REPO }} ssh:${{ inputs.FOLDER }}
      shell: bash 
    - name: 🍷 Executing commands...
      run: ssh ssh "${{ inputs.RUN }}; exit"
      shell: bash
