name: ssh-action-uwu
description: 'Run commands on your vps after deploy'
author: 'sebastianjnuwu'
branding:
  icon: 'terminal'
  color: 'gray-dark'

inputs:
  IP:
    description: ''
    required: true
  USER:
    description: ''
    required: true
  KEY:
    description: ''
    required: true
  RUN: 
    description: ''
    required: true

runs:
  using: 'composite'
  steps:
    - name: 🗿 Setting up ssh...
      run: |
        mkdir -p ~/.ssh/
        echo "${{ inputs.KEY }}" > ~/.ssh/ssh.key
        chmod 600 ~/.ssh/ssh.key
        cat >>~/.ssh/config <<END
        Host ssh
          HostName ${{ inputs.IP }}
          User ${{ inputs.USER }}
          Port 22
          IdentityFile ~/.ssh/ssh.key
          StrictHostKeyChecking no
        END
        
      shell: bash
    - name: 🍷 Executing commands...
      run: ssh ssh "${{ inputs.RUN }}; exit"
      shell: bash
